#version: '3.8'

services:
  #VERİTABANI
  db:
    image: postgres:15
    container_name: eczane_db
    environment:
      - POSTGRES_DB=eczane_db
      - POSTGRES_USER=kerem
      - POSTGRES_PASSWORD=Beyazpano123
    volumes:
      #Depolama hafıza bölümü
      - postgres_data:/var/lib/postgresql/data # Veriler silinmesin diye koruma
    networks:
      - eczane-net

  #VERİTABANI YÖNETİM PANELİ
  pgadmin:
    image: dpage/pgadmin4
    container_name: eczane_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=keremdmrbnt03@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Beyazpano123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - eczane-net

  #DJANGO 
  backend:
    build: .
    container_name: eczane_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Bilgisayarındaki kod değişikliğini anında içeri aktarma (Hot Reload)
    ports:
      - "8000:8000"
    depends_on:
      - db # Veritabanı açılmadan backend çalışmasın
    networks:
      - eczane-net

  #REDIS CACHE
  redis:
    image: redis:7-alpine
    container_name: eczane_redis
    ports:
      - "6379:6379"
    networks:
      - eczane-net

  # CELERY WORKER 
  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - eczane-net

  # CELERY BEAT 
  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - eczane-net

  # MAILPIT SAHTE E-POSTA KUTUSU
  mailpit:
    image: axllent/mailpit
    container_name: eczane_mailpit
    ports:
      - "8025:8025" # Web Arayüzü (http://localhost:8025)
      - "1025:1025" # SMTP Portu (Django buraya atacak)
    networks:
      - eczane-net

# OLUŞTURULACAK AĞLAR VE DEPOLAR
networks:
  eczane-net:
    driver: bridge

volumes:
  postgres_data:
