"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv #.env
from datetime import timedelta #JWT için süre ayarı

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-def-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'accounts',
    'inventory',
    'sales',
    'patients',
    'procurement',
    'rest_framework', #Backend ve Frontendin iletişimi için lazım
    'corsheaders',    #Cross-Origin Resource Sharing (Güvenlik Engeli)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',  #JWT'yi çalıştıran ana kütüphanemiz
    'rest_framework_simplejwt.token_blacklist', #Çıkış yapacak kişinin tokeni blackliste alınır süre dolmasa bile devre dışı kalır.
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', #Giriş Kartı herkese verecez sistemi doldurmayacağız.
    )
}

# JWT Ayarlarımız
SIMPLE_JWT_SIGNING_KEY = os.getenv("SIMPLE_JWT_SIGNING_KEY", os.getenv("SECRET_KEY", "django-insecure-please-change-me"))

ACCESS_TOKEN_TIMEOUT = int(os.getenv("ACCESS_TOKEN_TIMEOUT", 60 * 60))        # 1 Saat
REFRESH_TOKEN_TIMEOUT = int(os.getenv("REFRESH_TOKEN_TIMEOUT", 60 * 60 * 72)) # 72 Saat Login yapmak gerekir

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=ACCESS_TOKEN_TIMEOUT),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=REFRESH_TOKEN_TIMEOUT),
    'ROTATE_REFRESH_TOKENS': True,  #Yeni refresh token verir
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SIMPLE_JWT_SIGNING_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #Güvenlik Engeli -React ile alakalı
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', #Gelen JWT token'ı doğrular ve isteği yapan kullanıcıyı request.user olarak ayarlar.
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'eczane_db'),
        'USER': os.getenv('DB_USER', 'bitirme_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'bitirme_password'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# REDIS CACHE AYARLARI
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# CELERY AYARLARI
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_TIMEZONE = "Europe/Istanbul"

# CELERY BEAT AYARLARI 
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'stoklari-kontrol-et-her-dakika': {
        'task': 'inventory.mails.stock_alert.check_stock_metrics',
        'schedule': 43200.0, #Günde 2 kere ilaç kontrolü
    },
    'gunluk-ciro-raporu-gece-yarisi': {
        'task': 'sales.mails.daily_report.send_daily_sales_report',
        'schedule': crontab(hour=0, minute=0), # Her gece 00:00 tarihinde rapor gönderiyoruz
    },
    'haftalik-kampanya-maili-pazartesi-sabah': {
        'task': 'patients.mails.campaign.send_weekly_campaign_email',
        'schedule': crontab(day_of_week=1, hour=9, minute=0), # Pazartesi sabah 09:00
    },
    'haftalik-genel-rapor-pazartesi': {
        'task': 'inventory.mails.weekly_report.send_weekly_report',
        'schedule': crontab(day_of_week=1, hour=9, minute=0), # Pazartesi sabah 09:00
    },
}

"""
Mailpit simülasyonu için
EMAIL_HOST = 'mailpit'     # Docker servis adı
EMAIL_PORT = 1025          # Mailpit SMTP portu
EMAIL_USE_TLS = False      # Geliştirme ortamında şifreleme yok
DEFAULT_FROM_EMAIL = 'admin@eczane.com'
"""
# SMTP AYARLARI 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = True 
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')        
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#User Model 
AUTH_USER_MODEL = 'accounts.User'

# Frontend adresine güvenmek için
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost",
]

#çerezlere izin ver
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True