# Generated by Django 5.2.10 on 2026-01-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İlaç Adı')),
                ('expiry_date', models.DateField(verbose_name='Son Kullanma Tarihi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('form_type', models.CharField(choices=[('TABLET', 'Hap / Tablet'), ('LIQUID', 'Sıvı / Şurup'), ('OTHER', 'Diğer')], default='TABLET', max_length=10, verbose_name='Hap mı Sıvı mı?')),
            ],
        ),
    ]
