# Generated by Django 5.2.10 on 2026-01-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='how_many',
            field=models.IntegerField(default=0, verbose_name='Stok Adedi'),
        ),
    ]
