# Generated by Django 5.2.10 on 2026-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medicine_how_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='form_type',
            field=models.CharField(choices=[('TABLET', 'Hap / Tablet'), ('SIVI/ŞURUP', 'Sıvı / Şurup'), ('DİĞER', 'Diğer')], default='TABLET', max_length=10, verbose_name='Hap mı Sıvı mı?'),
        ),
    ]
