# Generated by Django 5.2.10 on 2026-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_medicine_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
