# Generated by Django 5.2.10 on 2026-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_medicine_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='form_type',
            field=models.CharField(choices=[('TABLET', 'Hap / Tablet'), ('LIQUID', 'Sıvı / Şurup'), ('OTHER', 'Diğer')], default='TABLET', max_length=10, verbose_name='Hap mı Sıvı mı?'),
        ),
    ]
