# Generated by Django 5.2.10 on 2026-02-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicine_form_type'),
        ('procurement', '0002_procurement_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.procurement', verbose_name='Tedarikçi'),
        ),
    ]
