# Generated by Django 5.2.10 on 2026-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
        ),
    ]
