# Generated by Django 5.2.12 on 2026-04-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='TC Kimlik Numarası'),
        ),
    ]
