# Generated by Django 5.2.12 on 2026-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tc',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='TC Kimlik Numarası'),
        ),
    ]
