# Generated by Django 5.2.10 on 2026-01-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tedarikçi Adı')),
                ('phone_number_proc', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('address_proc', models.TextField(blank=True, null=True, verbose_name='Adres')),
            ],
        ),
    ]
