# Generated by Django 5.2.10 on 2026-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta'),
        ),
    ]
