# Generated by Django 5.2.10 on 2026-01-31 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_email'),
        ('sales', '0002_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient', verbose_name='Müşteri'),
        ),
    ]
